# Generated by Django 5.1.4 on 2025-01-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdb',
            name='fourth',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testdb',
            name='second',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testdb',
            name='third',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
