# Generated by Django 3.1.3 on 2025-01-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0003_lawyer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Фотография'),
        ),
    ]
