# Generated by Django 3.1.3 on 2025-01-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0006_auto_20250111_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
